[grocy]
server_url = "https://de.demo.grocy.info"
api_key = ""

[sleep]
sleep_if_no_activity = true
sleep_after_secs = 30
activity_detection_mode = "motion"  # voice or motion

    [sleep.motion_detection]
    gpio_pir = 17  # BCM notation

    [sleep.voice_detection]
    detection_threshold = 30  # range: 2 - 1000

[scanner]
gpio_relais = 4  # BCM notation